tiendas_completas = [
    'VAD10_CAGUA', 'VAD10_MATURIN', 'VAD10_BARALT', 'VAD10_UPATA',
    'VAD10_CABIMAS', 'VAD10_BABILON', 'VAD10_CRUZVERDE', 'VAD10_PROPATRIA',
    'VAD10_KAPITANA', 'VAD10_VALERA', 'VAD10_VALENCIA', 'VAD10_CATIA',
    'VAD10_GUACARA', 'VAD10_CABUDARE', 'VAD10_GUANARE'
]

tiendas_simplificadas = [
    'CAGUA', 'MATURIN', 'BARALT', 'UPATA',
    'CABIMAS', 'BABILON', 'CRUZ VERDE', 'PROPATRIA',
    'KAPITANA', 'VALERA', 'VALENCIA', 'CATIA',
    'GUACARA', 'CABUDARE', 'GUANARE'
]
